const LOGGER_MESSAGES = {
  AUTHGURD_VALIDATEING: "validateToken - Token validation started",
  MISSING_TOKEN: "validateToken - Missing authorization header",
  VERIFICATION_FAILED: "validateToken - Token verification failed:",
  INVALID_FORMAT: "validateToken - Invalid token format",
  VALIDATION_FAILED: "validateToken - Error:",
  CONTROLLER: "Controller - ",
  SERVICE: "Service - ",
  USER_VALIDATION_UNSUCCESSFUL: "User validation failed",
  USER_VALIDATION_SUCCESSFUL: "User validation successful",
  REGISTER_USER: "Register user function initiated",
  REGISTER_USER_COMPLETED: "Register user function completed",
  REGISTER_USER_FAILED: "Register user function failed.",
  USER_CREATE: "User created successful",
  USER_CREATE_FAILED: "User create failed",
  LOGIN_USER: "User login function initiated",
  LOGIN_COMPLETED: "User login function completed.",
  LOGIN_FAILED: "User login function failed.",
  PROFILE_FETCH: "Fetch profile function initiated",
  PROFILE_FETCH_COMPLETED: "Fetch profile function completed.",
  PROFILE_FETCH_FAILED: "Fetch profile function failed.",
  PROFILE_UPDATE: "Update profile function initiated",
  PROFILE_UPDATE_COMPLETED: "Update profile function completed.",
  PROFILE_UPDATE_FAILED: "Update profile function failed.",
  EMAIL_SEND: "Email send successful",
  EMAIL_SEND_FAILED: "Email send failed",
  INVALID_EMAIL_OR_PASSWORD:
    "Invalid email or password. Please check your credentials and try again.",
  EXISTING_USER:
    "This user is already registered. Please choose a different email or sign in.",
  SECRET_CODE_SEND: "Secret code send function initiated",
  SECRET_CODE_SEND_COMPLETED: "Secret code send function completed",
  SECRET_CODE_SEND_FAILED: "Secret code send function failed.",
  USER_NOT_FOUND:
    "User not found. Please verify the entered Id or contact support for assistance.",
  EMAIL_VERIFY_PENDING:
    "Your email verification is pending. Please check your inbox for instructions.",
  PRODUCT_CREATION: "Product creation function initiated.",
  PRODUCT_CREATION_COMPLETED: "Product creation function completed.",
  PRODUCT_CREATION_FAILED: "Product creation function failed.",
  PRODUCT_UPDATE: "Product updating function initiated.",
  PRODUCT_UPDATE_COMPLETED: "Product updating function completed.",
  PRODUCT_UPDATE_FAILED: "Product updating function failed.",
  PRODUCTS_FETCH: "Products fetching function initiated.",
  PRODUCTS_FETCH_COMPLETED: "Products fetching function completed.",
  PRODUCTS_FETCH_FAILED: "Products fetching function failed.",
  QUICK_BUY_PRODUCTS_FETCH: "Quick buy Products fetching function initiated.",
  QUICK_BUY_PRODUCTS_FETCH_COMPLETED:
    "Quick buy Products fetching function completed.",
  QUICK_BUY_PRODUCTS_FETCH_FAILED:
    "Quick buy Products fetching function failed.",
  PRODUCT_FETCH: "Product fetching function initiated.",
  PRODUCT_FETCH_COMPLETED: "Product fetching function completed.",
  PRODUCT_FETCH_FAILED: "Product fetching function failed.",
  ORDER_DETAILS_FETCH: "Order details fetching function initiated.",
  ORDER_DETAILS_FETCH_COMPLETED: "Order details fetching function completed.",
  ORDER_DETAILS_FETCH_FAILED: "Order details fetching function failed.",
  ORDER_CREATION: "Order creation function initiated.",
  ORDER_CREATION_COMPLETED: "Order creation function completed.",
  ORDER_CREATION_FAILED: "Order creation function failed.",
  ORDER_FETCH: "Order fetch function initiated.",
  ORDER_FETCH_COMPLETED: "Order fetch function completed.",
  ORDER_FETCH_FAILED: "Order fetch function failed.",
  PRODUCT_DELETE: "Product deleting function initiated.",
  PRODUCT_DELETE_COMPLETED: "Product deleting function completed.",
  PRODUCT_DELETE_FAILED: "Product deleting function failed.",
  ADD_TO_CART: "Add to cart function initiated.",
  ADD_TO_CART_COMPLETED: "Add to cart function completed.",
  ADD_TO_CART_FAILED: "Add to cart function failed.",
  GET_CART_ITEMS: "Get cart items function initiated.",
  GET_CART_ITEMS_COMPLETED: "Get cart items function completed.",
  GET_CART_ITEMS_FAILED: "Get cart items function failed.",
};

module.exports = LOGGER_MESSAGES;
