const LOGGER_MESSAGES = {
  AUTHGURD_VALIDATEING: "validateToken - Token validation started",
  MISSING_TOKEN: "validateToken - Missing authorization header",
  VERIFICATION_FAILED: "validateToken - Token verification failed:",
  INVALID_FORMAT: "validateToken - Invalid token format",
  VALIDATION_FAILED: "validateToken - Error:",
  CONTROLLER: "Controller - ",
  SERVICE: "Service - ",
  USER_VALIDATION_UNSUCCESSFUL: "User validation failed",
  USER_VALIDATION_SUCCESSFUL: "User validation successful",
  REGISTER_USER: "Register user function initiated",
  REGISTER_USER_COMPLETED: "Register user function completed",
  REGISTER_USER_FAILED: "Register user function failed.",
  USER_CREATE: "User created successful",
  USER_CREATE_FAILED: "User create failed",
  LOGIN_USER: "User login function initiated",
  LOGIN_COMPLETED: "User login function completed.",
  LOGIN_FAILED: "User login function failed.",
  PROFILE_FETCH: "Fetch profile function initiated",
  PROFILE_FETCH_COMPLETED: "Fetch profile function completed.",
  PROFILE_FETCH_FAILED: "Fetch profile function failed.",
  PROFILE_UPDATE: "Update profile function initiated",
  PROFILE_UPDATE_COMPLETED: "Update profile function completed.",
  PROFILE_UPDATE_FAILED: "Update profile function failed.",
  ADDRESS_CREATION: "Address creation function initiated.",
  ADDRESS_CREATION_COMPLETED: "Address creation function completed.",
  ADDRESS_CREATION_FAILED: "Address creation function failed.",
  ADDRESS_UPDATE: "Update address function initiated.",
  ADDRESS_UPDATE_COMPLETED: "Update address function completed.",
  ADDRESS_UPDATE_FAILED: "Update address function failed.",
  ADDRESSES_FETCH: "Fetch addresses function initiated.",
  ADDRESSES_FETCH_COMPLETED: "Fetch addresses function completed.",
  ADDRESSES_FETCH_FAILED: "Fetch addresses function failed.",
  ADDRESS_DELETE: "Address deleting function initiated.",
  ADDRESS_DELETE_COMPLETED: "Address deleting function completed.",
  ADDRESS_DELETE_FAILED: "Address deleting function failed.",
  REVIEW_CREATION: "Review creation function initiated.",
  REVIEW_CREATION_COMPLETED: "Review creation function completed.",
  REVIEW_CREATION_FAILED: "Review creation function failed.",
  REVIEW_UPDATE: "Update review function initiated.",
  REVIEW_UPDATE_COMPLETED: "Update review function completed.",
  REVIEW_UPDATE_FAILED: "Update review function failed.",
  REVIEWS_FETCH: "Fetch reviews function initiated.",
  REVIEWS_FETCH_COMPLETED: "Fetch reviews function completed.",
  REVIEWS_FETCH_FAILED: "Fetch reviews function failed.",
  REVIEW_DELETE: "Review deleting function initiated.",
  REVIEW_DELETE_COMPLETED: "Review deleting function completed.",
  REVIEW_DELETE_FAILED: "Review deleting function failed.",
  EMAIL_SEND: "Email send successful",
  EMAIL_SEND_FAILED: "Email send failed",
  INVALID_EMAIL_OR_PASSWORD:
    "Invalid email or password. Please check your credentials and try again.",
  EXISTING_USER:
    "This user is already registered. Please choose a different email or sign in.",
  SECRET_CODE_SEND: "Secret code send function initiated",
  SECRET_CODE_SEND_COMPLETED: "Secret code send function completed",
  SECRET_CODE_SEND_FAILED: "Secret code send function failed.",
  USER_NOT_FOUND:
    "User not found. Please verify the entered Id or contact support for assistance.",
  EMAIL_VERIFY_PENDING:
    "Your email verification is pending. Please check your inbox for instructions.",
  PRODUCT_CREATION: "Product creation function initiated.",
  PRODUCT_CREATION_COMPLETED: "Product creation function completed.",
  PRODUCT_CREATION_FAILED: "Product creation function failed.",
  PRODUCT_UPDATE: "Product updating function initiated.",
  PRODUCT_UPDATE_COMPLETED: "Product updating function completed.",
  PRODUCT_UPDATE_FAILED: "Product updating function failed.",
  PRODUCTS_FETCH: "Products fetching function initiated.",
  PRODUCTS_FETCH_COMPLETED: "Products fetching function completed.",
  PRODUCTS_FETCH_FAILED: "Products fetching function failed.",
  CATEGORY_PRODUCTS_FETCH: "Category Products fetching function initiated.",
  CATEGORY_PRODUCTS_FETCH_COMPLETED:
    "Category Products fetching function completed.",
  CATEGORY_PRODUCTS_FETCH_FAILED: "Category Products fetching function failed.",
  RECENT_PRODUCTS_FETCH: "Recent Products fetching function initiated.",
  RECENT_PRODUCTS_FETCH_COMPLETED:
    "Recent Products fetching function completed.",
  RECENT_PRODUCTS_FETCH_FAILED: "Recent Products fetching function failed.",
  SIMILAR_PRODUCTS_FETCH: "Similar Products fetching function initiated.",
  SIMILAR_PRODUCTS_FETCH_COMPLETED:
    "Similar Products fetching function completed.",
  SIMILAR_PRODUCTS_FETCH_FAILED: "Similar Products fetching function failed.",
  QUICK_BUY_PRODUCTS_FETCH: "Quick buy Products fetching function initiated.",
  QUICK_BUY_PRODUCTS_FETCH_COMPLETED:
    "Quick buy Products fetching function completed.",
  QUICK_BUY_PRODUCTS_FETCH_FAILED:
    "Quick buy Products fetching function failed.",
  PRODUCT_FETCH: "Product fetching function initiated.",
  PRODUCT_FETCH_COMPLETED: "Product fetching function completed.",
  PRODUCT_FETCH_FAILED: "Product fetching function failed.",
  ORDER_DETAILS_FETCH: "Order details fetching function initiated.",
  ORDER_DETAILS_FETCH_COMPLETED: "Order details fetching function completed.",
  ORDER_DETAILS_FETCH_FAILED: "Order details fetching function failed.",
  ORDER_CREATION: "Order creation function initiated.",
  ORDER_CREATION_COMPLETED: "Order creation function completed.",
  ORDER_CREATION_FAILED: "Order creation function failed.",
  ORDER_FETCH: "Order fetch function initiated.",
  ORDER_FETCH_COMPLETED: "Order fetch function completed.",
  ORDER_FETCH_FAILED: "Order fetch function failed.",
  PRODUCT_DELETE: "Product deleting function initiated.",
  PRODUCT_DELETE_COMPLETED: "Product deleting function completed.",
  PRODUCT_DELETE_FAILED: "Product deleting function failed.",
  ADD_TO_CART: "Add to cart function initiated.",
  ADD_TO_CART_COMPLETED: "Add to cart function completed.",
  ADD_TO_CART_FAILED: "Add to cart function failed.",
  GET_CART_ITEMS: "Get cart items function initiated.",
  GET_CART_ITEMS_COMPLETED: "Get cart items function completed.",
  GET_CART_ITEMS_FAILED: "Get cart items function failed.",
};

module.exports = LOGGER_MESSAGES;
